apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-sample-demo
  labels:
    app: pythonapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: python-demo
        image: cmandava91/myapp:v2
        ports:
        - containerPort: 8000